### ISSUE TITLE
Como creador del evento quiero poder modificar/eliminar el evento

### ISSUE THREAD

**Issue by cromanalcaide** [cromanalcaide/web-api-event-planner#15]
Criterios:

- [x] El creador podrá acceder a un botón que elimine dicho evento
- [x] El creador podrá acceder a un botón para modificar los datos del evento
- [x] En el caso de eliminar, el creador deberá confirmar que quiere eliminar el evento
- [x] Creación endpoints PUT/DELETE en routes.py para Events

**Comment by lbdelilla** [comment]
Al momento todo lo anterior esta creado. El evento no se elimina solo cambia a un estado de inactivo para no perder datos.
